remote_theme: ddc-java/ddc-day-book
repository_link:
  enabled: false
page_navigator:
  enabled: true
titles_from_headings:
  enabled: false
prev_next_navigation:
- bottom

title: "Chat Project"
description: "Simple Chat application implemented as a RESTful service with an Android client."

author:
  name: "Deep Dive Java Enterprise & Android Mobile bootcamp cohort 21, with Nick Bennett and Reed Searle"

# Do not change the following line.
  copyright: true
